/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/


var nth_fib = function(n){	
	var i, f, f1, f2;
 	for (i = 0; i < n; i++){
		if (i === 0){
			f = 1; 
			f1 = f; 
		} else if(i === 1){
			f = 2; 
			f2 = f; 
		} else {
			f = f1 + f2; 
			f1 = f2; 
			f2 = f; 
		}
	}
	return f;				
};		
	
var sum_even_fib = function(a){
	var i, sum; 
	sum = 0; 
	for (i = 1; nth_fib(i) < a; i++){
		if (nth_fib(i)%2 === 0){
			sum = sum + nth_fib(i);
		}
	}
	return sum;
};

var test = function(){
	if (sum_even_fib(15) !== 10) {
		console.log('test #1 has failed');
	} else if (sum_even_fib(55) !== 44) {
		console.log('test #2 has failed');
	} else {
		console.log('it works like a fkn clock!');
	}
};
	
