// The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
// The first ten terms would be: 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

// Let us list the factors of the first seven triangle numbers:

// 1: 1
// 3: 1,3
// 6: 1,2,3,6
// 10: 1,2,5,10
// 15: 1,3,5,15
// 21: 1,3,7,21
// 28: 1,2,4,7,14,28
// We can see that 28 is the first triangle number to have over five divisors.

// What is the value of the first triangle number to have over five hundred divisors?

var factors = function(x) {
	var factors, i, a; 
	factors = []; 
	a = 0;
	for (i = 1; i <= x/2; i++) {
		if (x%i === 0){
			factors[a] = i;
			a = a + 1;
			if (x/i <= i) {
				return factors;
			}
			factors[a] = x/i; 
			a = a + 1; 
		}
		
	}
	return factors;
};

var highly_divisible_triangular_number = function(n) {
	var triangle_number, i, f; 
	triangle_number = 0; 
	i = 1; 
	while (true) {
		triangle_number = triangle_number + i; 
		if (triangle_number > n*2){
			f = factors(triangle_number); 
			if (f.length > n) {
				return triangle_number; 
			}
		}
		i = i + 1; 
	}
}

var test = function() {
	if (highly_divisible_triangular_number(1)!==3) {
		console.log('test #1 has failed'); 
	} else if (highly_divisible_triangular_number(5)!==28) {
		console.log('test #2 has failed'); 
	} else if (highly_divisible_triangular_number(500)!==76576500) {
		console.log('test #3 has failed'); 
	} else {
		console.log('it works like a fkn clock!');
	}
};
